### ISSUE TITLE
Full Screen mode stopping the  program to be responing

### ISSUE THREAD

**Issue by MohamedElgamal** [ceccopierangiolieugenio/pyTermTk#153]
when firstly run the program the terminal size takes the size of the content but when i try to press full screen button then nothing in the terminal is clickable buttons and layout 
me trying to run the program at first time :
![the_terminal_before_full_screen](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/25607813/89cfa722-2215-4782-a654-ebd23864904b)

after click full screen button when i try to change the fields nothing change and responding : 

![terminal_after_full_screen](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/25607813/c2b1a826-5a23-4913-9b95-7641de54f4ba)

my code : 
<pre>
import TermTk as TTK
from yamlfilereader import YamlFileReader

# Defining the Object that will handle the yaml file
yamlFileReader = YamlFileReader()
call_center_name = yamlFileReader.extract_call_center()
welcome_message = f"welcome to {call_center_name}"
# item_list holds the EditLine objects
item_list = []

# Function Call that will handle the event click on the issue to be forwarded to its screen
def on_issue_btn_click(issue_title):
    pass

def on_submit_btn_clicked(itemlist):
    for item in itemlist:
        print(f"item : " + str(item._text))
def create_tab_layout(text):
    layout = TTK.TTkVBoxLayout()
    for field in yamlFileReader.search_for_issue_by_title(title)[1]:
        # field_continaer will hold the lable and input_field to add it to a HBox to display it as one line
        field_container = TTK.TTkFrame(layout=TTK.TTkHBoxLayout() )
        label = TTK.TTkLabel(text=f"*{field}", maxWidth=15)
        input_field = TTK.TTkLineEdit()
        item_list.append(input_field)
        field_container.layout().addWidget(label)
        field_container.layout().addWidget(input_field)
        layout.addWidget(field_container)
    submit_btn = TTK.TTkButton(text="Submit")
    submit_btn.clicked.connect(lambda item_list=item_list.copy(): on_submit_btn_clicked(item_list))
    layout.addWidget(submit_btn)
    item_list.clear()
    return layout

# Setting the layout
# Reference Link for Docs to Explain the Layouts
# https://ceccopierangiolieugenio.github.io/pyTermTk/tutorial/002-layout.html

boxLayout = TTK.TTkVBoxLayout()
root = TTK.TTk(layout=boxLayout, title=call_center_name )

# Defining Welcome Label and Binding it to screen
welcome_label = TTK.TTkLabel(text=welcome_message, maxHeight=1)
boxLayout.addWidget(welcome_label)
titles = yamlFileReader.extract_issue_titles()
tab_widget = TTK.TTkTabWidget()
for title in titles:
    tab_frame = TTK.TTkFrame()
    tab_frame.setLayout(create_tab_layout(title))  # Pass the title argument here
    tab_widget.addTab(tab_frame, title)
    # button = TTK.TTkButton(parent= root, border=True, text=title, maxWidth=30, maxHeight=3)
    # button.clicked.connect(lambda: on_issue_btn_click(title))
    #boxLayout.addWidget(button)
boxLayout.addWidget(tab_widget)
boxLayout._alignment
root.mainloop()
</pre>

**Comment by ceccopierangiolieugenio** [comment]
Unfortunately I cannot run your code.
I suspect that multiple resize events (there is a bug I have to address about this)
are sent by the terminal when you maximize,
does the app works if you manually resize the terminal?

**Comment by MohamedElgamal** [comment]
Yes the app is working when i resize the teminal manually 
If it is a bug how i can fix it because it is production task and looking to achieve all requirements

**Comment by ceccopierangiolieugenio** [comment]
still the yamlfilereader is missing, is it a custom file?

**Comment by MohamedElgamal** [comment]
sorry i updated my repo 
https://github.com/MohamedElgamal/Techrq
you can try it now

**Comment by ceccopierangiolieugenio** [comment]
no worries, I managed to run it, anyway, which terminal are you using?

I tried gnome-terminal as well and It is working.
Anyway, I'll try to make that fix tomorrow hopefully it will solve this problem

**Comment by MohamedElgamal** [comment]
i am using xterm-256color terminal my linux os is ubentu i waiting for your response to me

**Comment by ceccopierangiolieugenio** [comment]
PyTermTk: v**0.30.0a128** should fix it

**Comment by MohamedElgamal** [comment]
i am happy you are trying to help to and for your fast response to me 
but the problem still appears to me 
i am included a video that describe the problem during the running
[full screen mode.webm](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/25607813/ca2f2ae7-df03-49be-b42d-fa01c18a812b)

**Comment by ceccopierangiolieugenio** [comment]
Unfortunately 
I notice in your video that you have the session.log,
can you attach here?

**Comment by ceccopierangiolieugenio** [comment]
I managed to reproduce the issue with the old one 
same issue does not happen if I upgrade it as shown in this video:

https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/42fd8155-4527-4e89-a1b1-33dbf2bce50f

Did you upgrade it?

**Comment by MohamedElgamal** [comment]
yes i managed to update the package before testing it again
it is the terminal result for updating which show its already updated 
![Screenshot from 2023-07-29 19-46-00](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/25607813/452ab23b-bf37-484f-82d6-1165a6330feb)
and this is the session log file 
[session.log](https://github.com/ceccopierangiolieugenio/pyTermTk/files/12244051/session.log)

I am waiting for your response because this functionality is important to me

**Comment by MohamedElgamal** [comment]
when i tried your step it actually work i don't know where the problem come from i attached your requested files
[session.log](https://github.com/ceccopierangiolieugenio/pyTermTk/files/12245131/session.log)
[stacktrace.txt](https://github.com/ceccopierangiolieugenio/pyTermTk/files/12245132/stacktrace.txt)

also i notice something that not a big issue when i am press submit button the layout take the size of full screen automatically ( the layout size growth to the right direction )  

thanks for your help and your time

**Comment by ceccopierangiolieugenio** [comment]
That is because each label is a full object and all of them try to use the all the space available 
and the labels itselfforce their size as the minimum usable
to overcame this you can use a logViewer and log there instead of using the labels:

```python
import TermTk as TTK
import getpass
from yamlfilereader import YamlFileReader

# Defining the Object that will handle the yaml file
yamlFileReader = YamlFileReader()
call_center_name = yamlFileReader.extract_call_center()

# Act as container that hold the references of input fields to process it at form submission
item_list = []


# Returning the Name of current logged in user
def get_current_username():
    return getpass.getuser()

welcome_message = f"welcome ,{get_current_username()} ,at {call_center_name}"


#  Responsible for processing form data entered by user when clicking on submit button
# The implementation will be added based on the next requirement
def on_submit_btn_clicked(itemlist):
    for item in itemlist:
        #################################################################
        #################################################################
        ####################  Here I am logging  ########################
        #################################################################
        #################################################################
        TTK.TTkLog.debug(f"input field obj :  {item} has text value = {item._text }")

def create_tab_layout(text):
    layout = TTK.TTkVBoxLayout(borderColor=TTK.TTkColor.fg('#00FF00'))
    for field in yamlFileReader.search_for_issue_by_title(title)[1]:
        # field_continaer will hold the lable and input_field to add it to a HBox to display it as one line
        field_container = TTK.TTkFrame(layout=TTK.TTkHBoxLayout())
        label = TTK.TTkLabel(text=f"*{field}", maxWidth=15 ,color=TTK.TTkColor.fg('#00FF00'))
        input_field = TTK.TTkLineEdit()
        item_list.append(input_field)
        field_container.layout().addWidget(label)
        field_container.layout().addWidget(input_field)
        layout.addWidget(field_container)
    submit_btn = TTK.TTkButton(text="Submit" ,color=TTK.TTkColor.fg('#00FF00') ,
                               borderColor=TTK.TTkColor.fg('#00FF00'),border=True , maxHeight=3
                               )
    submit_btn.clicked.connect(lambda item_list=item_list.copy(): on_submit_btn_clicked(item_list))
    layout.addWidget(submit_btn)
    item_list.clear()
    return layout

# Setting the layout
# Reference Link to Docs to Explain the Layouts
# https://ceccopierangiolieugenio.github.io/pyTermTk/tutorial/002-layout.html

boxLayout = TTK.TTkVBoxLayout()
root = TTK.TTk(layout=boxLayout, title=call_center_name )

# Defining Welcome Label and Binding it to screen
welcome_label = TTK.TTkLabel(text=welcome_message, maxHeight=1)
boxLayout.addWidget(welcome_label)
titles = yamlFileReader.extract_issue_titles()
tab_widget = TTK.TTkTabWidget()
for title in titles:
    tab_frame = TTK.TTkFrame()
    tab_frame.setLayout(create_tab_layout(title))  # Pass the title argument here
    tab_widget.addTab(tab_frame, title)
boxLayout.addWidget(tab_widget)

#################################################################
#################################################################
########### A log Viewer is placed at the bottom ################
#################################################################
#################################################################
boxLayout.addWidget(TTK.TTkLogViewer())

root.mainloop()

```
